name: Build C++ Program

on:
  push:
    branches: [branchMake]
  pull_request:
    branches: [branchMake]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y g++ make

      - name: Make
        run: make