name: Build C++ Program

on:
  push:
    branches: [branchAutoPackage]
  pull_request:
    branches: [branchAutoPackage]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make autoconf automake devscripts debhelper build-essential

      - name: Run Autoreconf
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Compile Program
        run: make

      - name: Build Debian Package
        run: dpkg-buildpackage -us -uc

      - name: Move Debian Package
        run: mv ../cppfuncaproject_1.0-1_amd64.deb .

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: cppfuncaproject-deb
          path: cppfuncaproject_1.0-1_amd64.deb
