name: Build and Test C++ Program

on:
  push:
    branches: [branchAutoTest]
  pull_request:
    branches: [branchAutoTest]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make autoconf automake build-essential

      - name: Run Autoreconf
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Compile Program
        run: make

      - name: Run Tests
        run: make check
